version: '3'

services:

  sql.data:
    image: mssql-linux
    build:
      context: ./DataBaseDeploy
      dockerfile: Dockerfile
    ports:
      - "5433:1433"
    container_name: mssql-linux 

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"    
    depends_on:
      - sql.data
  

   
 